#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y build-essential
#sudo apt-get install -y libprotobuf-dev protobuf-compiler && \
sudo apt-get install -y cmake
sudo apt-get install -y git
sudo apt-get install -y gcc-multilib